version: 2.1

workflows:
  build_and_test:
    jobs:
      - build
      - blendnet_test:
          blender_version: "2.80" # The first one supported
      - blendnet_test:
          blender_version: lts
      - blendnet_test:
          blender_version: latest # Latest release available

  nightly_test:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - blendnet_test:
          blender_version: "2.80" # The first one supported
      - blendnet_test:
          blender_version: lts
      - blendnet_test:
          blender_version: latest # Latest release available

jobs:
  build:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout:
          path: blendnet

      - run:
          name: Packing dist archive
          command: blendnet/.circleci/build.sh

      # TODO: run static tests
      #- store_test_results:
      #    path: results/reports

      - store_artifacts:
          path: results
          destination: results

  blendnet_test:
    parameters:
      blender_version:
        description: |
          Blender version to use
          * <version> - exact version you need
          * lts    - latest available LTS version
          * latest - latest available version
        type: string
    docker:
      - image: cimg/base:stable-20.04

    steps:
      - checkout:
          path: blendnet

      - setup_remote_docker

      - run:
          name: Preparing to the test execution
          command: |
            blendnet/.circleci/test_prepare.sh "<< parameters.blender_version >>"
            # Creating the docker container to store the data
            docker create -v /srv --name blendnet-srv alpine /bin/true
            docker cp blendnet blendnet-srv:/srv
            docker cp blender blendnet-srv:/srv
            docker cp workspace blendnet-srv:/srv
            mkdir -p results
          no_output_timeout: 5m

      - run:
          name: Run blendnet-manager
          background: true
          command: |
            # Run Manager for max 10 minutes
            timeout -k 5 360 docker run --name blendnet-manager -m 2G --rm -it \
                --volumes-from blendnet-srv ubuntu:20.04 \
                /srv/workspace/test_run_service.sh manager 2>&1 | tee results/manager.log || true
            echo "Check exceptions in the log"
            grep -q -v '^Traceback' results/manager.log
            echo "Check errors in the log"
            grep -q -v '^ERROR: ' results/manager.log

      - run:
          name: Run blendnet-agent-1
          background: true
          command: |
            # Run Agent for max 10 minutes
            timeout -k 5 360 docker run --name blendnet-agent-1 -m 2G --rm -it \
                --volumes-from blendnet-srv ubuntu:20.04 \
                /srv/workspace/test_run_service.sh agent 2>&1 | tee results/agent-1.log || true
            echo "Check exceptions in the log"
            grep -q -v '^Traceback' results/agent-1.log
            echo "Check errors in the log"
            grep -q -v '^ERROR: ' results/agent-1.log

      - run:
          name: Run blendnet-agent-2
          background: true
          command: |
            # Run Agent for max 10 minutes
            timeout -k 5 360 docker run --name blendnet-agent-2 -m 2G --rm -it \
                --volumes-from blendnet-srv ubuntu:20.04 \
                /srv/workspace/test_run_service.sh agent 2>&1 | tee results/agent-2.log || true
            echo "Check exceptions in the log"
            grep -q -v '^Traceback' results/agent-2.log
            echo "Check errors in the log"
            grep -q -v '^ERROR: ' results/agent-2.log

      - run:
          name: Run test blend file render
          command: blendnet/.circleci/test_execute.sh "<< parameters.blender_version >>"

      - run:
          name: Clean the docker containers
          when: always
          command: |
            # TODO: when BN-64 is completed - stop Manager and Agents properly
            docker rm -f blendnet-agent-1 || true
            docker rm -f blendnet-agent-2 || true
            docker rm -f blendnet-manager || true
            docker rm -f blendnet-srv || true

      # TODO: Add test results
      #- store_test_results:
      #    path: results/reports

      - store_artifacts:
          path: results
          destination: results
